apiVersion: v1
kind: Secret
metadata:
  name: ahmedelbaz-secrets
  namespace: ahmedelbaz
type: Opaque
stringData:
  DATABASE_URL: "mysql://avnadmin:AVNS_RvRDaxAOax6wdYg0GEI@elbaz-lms-ahmdelbaz.h.aivencloud.com:27038/defaultdb?ssl-mode=REQUIRED"
  JWT_SECRET: "CHANGE_ME_JWT_SECRET_32_CHAR_MIN"
  RESEND_API_KEY: "re_CHANGE_ME_RESEND_API_KEY"
  CLOUDFLARE_API_TOKEN: "CHANGE_ME_CF_API_TOKEN"
  R2_ACCESS_KEY: "CHANGE_ME_R2_ACCESS_KEY"
  R2_SECRET_KEY: "CHANGE_ME_R2_SECRET_KEY"
  ADMIN_EMAIL: "admin@ahmedelbaz.qzz.io"
