apiVersion: v1
kind: ConfigMap
metadata:
  name: ahmedelbaz-config
  namespace: ahmedelbaz
data:
  NODE_ENV: "production"
  PORT: "3001"
  DATABASE_HOST: "elbaz-lms-ahmdelbaz.h.aivencloud.com"
  DATABASE_PORT: "27038"
  DATABASE_NAME: "defaultdb"
  DATABASE_USER: "avnadmin"
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  R2_BUCKET: "ahmedelbaz-media"
  R2_ENDPOINT: "https://CHANGE_ME_ACCOUNT_ID.r2.cloudflarestorage.com"
  DOMAIN: "ahmedelbaz.qzz.io"
  CORS_ORIGIN: "https://ahmedelbaz.qzz.io"
