apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-app-sa
  namespace: ahmedelbaz
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup-sa
  namespace: ahmedelbaz
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-auditor-sa
  namespace: ahmedelbaz
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-collector-sa
  namespace: ahmedelbaz
automountServiceAccountToken: true
