apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: ahmedelbaz
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.52
          args:
            - --collector.otlp.enabled=true
            - --collector.otlp.http.host-port=0.0.0.0:4318
            - --collector.otlp.grpc.host-port=0.0.0.0:4317
            - --query.base-path=/
            - --storage.memory=true
          ports:
            - name: ui
              containerPort: 16686
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          securityContext:
            runAsUser: 65534
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: ahmedelbaz
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    app: jaeger
